### ISSUE TITLE
Integrate with ReSharper disable once features

### ISSUE THREAD

**Issue by mwpowellhtx** [MrJul/ForTea#58]
Hands down, AWESOME text translation framework you have going on here. Thank you!

I do not know if this is possible.

Basically, I get warnings like "Use string interpolation expression", but the template is embedded within 2013, not 2015. 2015 is an option but I haven't migrated there, yet; for now I am productive with 2013.

```C#
var formattedNames = string.Join(", ", from x in valueNames select string.Format(@"""{0}""", x));
                                                                   ^^^^^^^^^^^^^
return string.Format(@"                yield return new[] {{{0}}};", formattedNames);
       ^^^^^^^^^^^^^
```

Would be great to add comments such as:

```C#
// ReSharper disable once UseStringInterpolationExpression
```

Supposing that was the name of the rule.

**Comment by MrJul** [comment]
I don't think it's easy to do so right now because ReSharper implicitly uses the containing project language version. I'll have a look and open a issue in ReSharper if I can't solve this.

**Comment by citizenmatt** [comment]
Yep, ReSharper uses the C# language level of the project. By default, this isn't specified explicitly, and becomes the default value for Visual Studio - so VS2013 will be C#5 and VS2015 will be C#6. You can explicitly set it using the project properties page &rarr; Build &rarr; Advanced &rarr; Language Version. This will write a property to the .csproj file, and ReSharper will respect this. If you select C#5, you won't see C#6 features, such as prompting for string interpolation.

There is also a ReSharper override setting, that lets you target C#6, but tell ReSharper to treat it as C#5 (this is useful for projects that are auto-generated without a target language version, but which need to be C#5, such as Unity projects). You can get to this by showing the properties window with the project selected in the solution explorer (not right clicking and selecting properties, because that's too obvious). You'll see a property grid, where you can set the language level.

**Comment by MrJul** [comment]
Thank you for the explanation Matt.

There's bad news though: T4 files in VS2015 don't seem to use C# 6! However, since the containing project .cs files can use C# 6, the language level can't be changed at the project level. I didn't find a way to flag some PSI file with a specific language level, it's always at the project level.

**Comment by mwpowellhtx** [comment]
What I am saying is that C# 6 suggestions are happening for C# 5.

**Comment by mwpowellhtx** [comment]
Perhaps the logic is fouled between VS versions?

**Comment by mwpowellhtx** [comment]
![t4-vs2013-use-string-interpolation-expression](https://cloud.githubusercontent.com/assets/1824187/11042363/9f4f3926-86e4-11e5-804d-621ca4b01eaa.png)

**Comment by citizenmatt** [comment]
Yeah, that is a different issue. As far as I can see, there isn't a way to mark a file as C#5 only, you can only do it per-project. So there isn't a good way to get rid of these warnings as it stands. I've added an issue ([RSRP-450646](https://youtrack.jetbrains.com/issue/RSRP-450646)) to track this.

**Comment by mwpowellhtx** [comment]
@citizenmatt Cool thanks. Reading these reports, it seems to me that the language defaults are at least reversed from what they should be. I call that a bug, however innocent it may be. It can cause problems to the unsuspecting. I did find the settings in my project, but have *never* had to set them before. Somehow is seeing 13/5 as 15/6 and vice versa.

**Comment by citizenmatt** [comment]
I don't think anything is reversed. These two issues (the one I linked, and the one it's related to) are about running in VS2015 - the default project is set to C#6, so ReSharper uses that, and generally everything is fine. (And in VS2013, the default is C#5, as it should be). The problems appear to be only in T4 and Razor files, which apparently only support C#5. Because ReSharper's C# language level is project wide, the C# "islands" inside a T4 or Razor file are also considered to be C#6, so you get the newer suggestions.

I'd consider the Razor issue a bug, because we should have spotted it before shipping - we're making suggestions in the shipping project that won't work. I wouldn't call the T4 issue a bug, more of a feature waiting to happen :)

**Comment by mwpowellhtx** [comment]
I'm not sure I completely understood all that; it can get confusing which sandboxes, islands, etc, are involved. So VS2013 C# 6 suggestions versus VS2015 C# 5 suggestions isn't reversed? Okay, if you say so (sarcasm; I'm not buying that excuse). As long as it's known and something is being done about it.

**Comment by citizenmatt** [comment]
Oh, hang on. I missed that you're seeing C#6 suggestions in VS2013.

I thought you were seeing C#6 suggestions (in VS2015) in T4, which can only have C#5.

I'll investigate. Do you have a repro for VS2013 solution that shows this?

**Comment by mwpowellhtx** [comment]
Please pay attention. That's precisely what's being reported on the whole.

**Comment by MrJul** [comment]
Both issues might be related since's there a fake project involved with ForTea. Are your T4 files inside or outside a project?

**Comment by mwpowellhtx** [comment]
As I reported, I have a VS2013 project, in which the T4 file is a part, yes, "compiling" with the custom tool. The only other thing that would be great there is to somehow identify T4 dependency files; i.e. refresh when those dependencies are detected, but this is more of a T4 issue I think (?).

**Comment by citizenmatt** [comment]
@MrJul if you return an `IProject` from [`IPsiModule.ContainingProjectModule`](https://github.com/MrJul/ForTea/blob/548882de8cf49e3ed9db8c82bad63fc921ef189a/GammaJul.ReSharper.ForTea/Psi/T4PsiModule.cs#L119), you will get the chance to influence the C# language level. If you return `null`, as you're doing now, it'll default to C#6.

If you set the T4 module's owning project to the project that also owns the .tt file, I think that should do it. The T4 file would inherit the settings of the parent - and the VS2013 file would be C#5, or whatever the owning project was set to. You could possibly try and fake it, by implementing your own `IProject`, and you'd have to also call `CSharpLanguageLevelProjectProperty.SetLanguageLevel`. I'm not sure if you'll hit any other issues, though. It doesn't look like ReSharper does anything like this.

**Comment by MrJul** [comment]
@mwpowellhtx Thank you for the additional information.

@citizenmatt I've done that previously, but there were issues, mostly exceptions (can't remember which ones on the top on my head) since ReSharper asserts things about the project. I'll try again and let you know what was wrong.

**Comment by mwpowellhtx** [comment]
@MyJul No problem. Sounds like the joys of working within a plugin environment. Thanks for looking into it.

**Comment by MrJul** [comment]
Since ReSharper 2016.1 has added support for this, ForTea 1.6.0 will use the correct C# version inside T4 files depending on the VS version:
 - C# 4.0 in VS2010
 - C# 5.0 in VS2012 / VS2013 / VS2015 before Update 2
 - C# 6.0 in VS2015 Update 2 or later
